### ISSUE TITLE
iis_app cannot be created if its the only iis_app at the time of creation.

### ISSUE THREAD

**Issue by RossMurr4y** [RossMurr4y/puppet-iis#7]
When including an iis_app resource within a manifest, the Puppet run will fail at the point of trying to create the iis_app if there are currently no others.

Error: Failed to apply catalog: A JSON text must at least contain two octets!
c:/program files/Puppet Labs/Puppet/sys/ruby/lib/ruby/2.1.0/json/common.rb:155:in 'initialize'
c:/program files/Puppet Labs/Puppet/sys/ruby/lib/ruby/2.1.0/json/common.rb:155:in 'new'
c:/program files/Puppet Labs/Puppet/sys/ruby/lib/ruby/2.1.0/json/common.rb:155:in 'parse'
c:/ProgramData/PuppetLAbs/puppet/cache/lib/puppet/provider/iis_app/powershell.rb:31:in 'instances'
c:/ProgramData/PuppetLAbs/puppet/cache/lib/puppet/provider/iis_app/powershell.rb:21:in 'prefetch'

**Comment by RossMurr4y** [comment]
Have pushed a change for this to the Development branch. To be tested still.

**Comment by RossMurr4y** [comment]
Tested. Issue remains.

**Comment by RossMurr4y** [comment]
Have discovered the cause and fix for this. Previous fix was fine, testing conditions were not.
This is a problem with the JSON Parsing during self.instances method. It impacts all of the resource types however only gets seen on the iis_app as IIS has other resource types installed by default aka 'Default Web Site' etc.

Adding to this fix a fix for all resource types. Then testing.

**Comment by RossMurr4y** [comment]
resolved: https://github.com/RossMurr4y/iis/pull/15
